class Spelunk < Formula
  desc "Code intelligence for AI agents — persistent memory, code graph, search"
  homepage "https://github.com/spelunk-cloud/spelunk"
  license "MIT"
  version "0.8.1"

  # Install:
  #   brew install spelunk-cloud/spelunk/spelunk
  #
  # This file is generated by update-homebrew-formula.js in
  # spelunk-cloud/spelunk, invoked from the update-homebrew-formula job in
  # .github/workflows/release.yml on every stable tag push, and pushed here
  # automatically. Do not hand-edit the version/sha256 values — they will be
  # overwritten on the next release.
  #
  # Note: x86_64-apple-darwin (Intel Mac) is no longer offered as a prebuilt
  # target — Apple deprecated the architecture and it has not shipped on new
  # hardware in years. Intel Mac users should build from source; see
  # docs/getting-started.md.

  on_macos do
    on_arm do
      url "https://github.com/spelunk-cloud/spelunk/releases/download/v#{version}/spelunk-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "3bd5783f79d433b3f5016e3e3821b39d14ea51558b8df3e6a906b9b4e7d4594c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/spelunk-cloud/spelunk/releases/download/v#{version}/spelunk-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ad3203dcdd215f525866f5144fee63846df26190b249ff52d1020038bffcf4dd"
    end
    on_intel do
      url "https://github.com/spelunk-cloud/spelunk/releases/download/v#{version}/spelunk-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0f3746b6cc2a8ca27d3588f2d2e7b3269ad4225accf1b1e06eb51f85507f8f14"
    end
  end

  def install
    bin.install "spelunk"
    bin.install "spelunk-server"
  end

  test do
    system "#{bin}/spelunk", "--version"
  end

  def caveats
    <<~EOS
      Run `spelunk init` in a project directory to get started.
      To start the local server: `spelunk server start`
    EOS
  end
end
