class Spelunk < Formula
  desc "Code intelligence for AI agents — persistent memory, code graph, search"
  homepage "https://github.com/spelunk-cloud/spelunk"
  license "MIT"
  version "0.8.0"

  # Install:
  #   brew install spelunk-cloud/spelunk/spelunk
  #
  # This file is generated by update-homebrew-formula.js in
  # spelunk-cloud/spelunk, invoked from the update-homebrew-formula job in
  # .github/workflows/release.yml on every stable tag push, and pushed here
  # automatically. Do not hand-edit the version/sha256 values — they will be
  # overwritten on the next release.
  #
  # Note: x86_64-apple-darwin (Intel Mac) is no longer offered as a prebuilt
  # target — Apple deprecated the architecture and it has not shipped on new
  # hardware in years. Intel Mac users should build from source; see
  # docs/getting-started.md.

  on_macos do
    on_arm do
      url "https://github.com/spelunk-cloud/spelunk/releases/download/v#{version}/spelunk-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "e66c94ca649799bf19f07482925a737bfdc9a05a07ab1f7a2d6a75f6433c2c06"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/spelunk-cloud/spelunk/releases/download/v#{version}/spelunk-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "caab7742a06985f51ecb3b8634fc4edaec3d650a1dc801be86cbb087d4ffc364"
    end
    on_intel do
      url "https://github.com/spelunk-cloud/spelunk/releases/download/v#{version}/spelunk-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d6e76283c019bc4b175ecae879a0124b360c0fbc327404f4819c4a83debfbec3"
    end
  end

  def install
    bin.install "spelunk"
    bin.install "spelunk-server"
  end

  test do
    system "#{bin}/spelunk", "--version"
  end

  def caveats
    <<~EOS
      Run `spelunk init` in a project directory to get started.
      To start the local server: `spelunk server start`
    EOS
  end
end
